version: "3.8"
services:
    db:
        image: amazon/dynamodb-local
        ports:
            - "9000:8000"
    app:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - db
